export const GET_CME_DATA_SUCCESS = "GET_CME_DATA_SUCCESS";
export const GET_CME_DATA_FAILED = "GET_CME_DATA_FAILED";
export const GET_FLR_DATA_SUCCESS = "GET_FLR_DATA_SUCCESS";
export const GET_FLR_DATA_FAILED = "GET_FLR_DATA_FAILED";
export const GET_GST_DATA_SUCCESS = "GET_GST_DATA_SUCCESS";
export const GET_GST_DATA_FAILED = "GET_GST_DATA_FAILED";
